spring:
  datasource:
    # Use `localhost` instead of `*-database` when running a local PostgreSQL instance.
    url: 'jdbc:postgresql://renameme-database:5432/renameme'
    username: 'postgres'
    password: 'password'
  liquibase:
    change-log: classpath:db/changelog-main.xml
  jpa:
    hibernate:
      # Don't create/modify databases by inferring its properties from the models.
      ddl-auto: 'none'
    # See: https://stackoverflow.com/a/48222934/10620237
    open-in-view: false

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    info:
      enabled: true
