version: '3.8'

services:
  renameme:
    container_name: renameme
    image: renameme
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - 8000:8000
      - 8080:8080
    networks:
      - renameme-network
    links:
      - renameme-database
    depends_on:
      - renameme-database

  renameme-database:
    container_name: renameme-database
    image: postgres
    networks:
      - renameme-network
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=renameme
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

networks:
  renameme-network:
    driver: bridge
