name: ShellCheck

on:
  push:
    paths:
      - '**.sh'
      - '.github/workflows/*.yml'

jobs:
  shellcheck:
    name: 'ShellCheck'
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2

      - name: ShellCheck annotations
        uses: reviewdog/action-shellcheck@v1
        with:
          reporter: github-pr-check
          level: info
          exclude: |
            .git/*
            gradle/*
            gradlew
