name: Unit and Integration Tests

on:
  push:
    paths:
      - '.github/workflows/unit-and-integration-tests.yml'
      - 'bin/apply_migrations.sh'
      - 'bin/integration_tests.sh'
      - 'src/main/**.java'
      - 'src/main/resources/application.yml'
      - 'src/main/resources/*.xml'
      - '*.gradle'

env:
  GRADLE_CACHE: cache-gradle
  TMP_CACHE: cache-tmp
  INTEGRATION_TESTS_ENABLED: true

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-build-${{ env.GRADLE_CACHE }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.GRADLE_CACHE }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          architecture: x64

      - name: Grant Gradle wrapper (gradlew) sufficient permissions
        run: chmod +x ./gradlew

      - name: Build the project
        run: ./gradlew build

      - name: Run unit tests
        run: ./gradlew test

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-build-${{ env.GRADLE_CACHE }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.GRADLE_CACHE }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Cache ./tmp/*
        uses: actions/cache@v2
        with:
          path: ./tmp
          key: ${{ runner.os }}-build-${{ env.TMP_CACHE }}-${{ hashFiles('./tmp/*') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.TMP_CACHE }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          architecture: x64

      - name: Grant Gradle wrapper (gradlew) sufficient permissions
        run: chmod +x ./gradlew

      - name: Build the project
        run: ./gradlew build

      - name: Run integration tests
        run: ./bin/integration_tests.sh
